INFO 2018-04-27 15:17:38,544 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1638: 登录初始化2-2018_4_27_15_14_14.py:PASS:[time_consuming:0.273585]{ response : 'resultCode: 0' }
ERROR 2018-04-27 15:19:44,200 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1652: 登录初始化2-2018_4_27_15_14_14.py:FAILED: error message [', "[By casuse: expected_value:{'resultCode': 0, 'maxRetryCount': 5}, server_response_values:{'resultCode': 0, 'maxRetryCount': 1} ]", "{u'body': {u'ubt': {u'maxUploadSize': 100, u'sleepTime': 10000, u'minUploadSize': 10, u'basePageTrace': True, u'minUploadTime': 9999, u'maxRetryCount': 1}, u'schema': {u'shareBlackList': [u'http://mobtest.2boss.cn/app_qa/dist/index.html#/index', u'http://mob.2boss.cn/app_qa/dist/index.html#/index', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/hotperson_detail?', u'http://mob.2boss.cn/app_qa/dist/index.html#/hotperson_detail?', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/newpost_one?', u'http://mob.2boss.cn/app_qa/dist/index.html#/newpost_one?', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/newpost?', u'http://mob.2boss.cn/app_qa/dist/index.html#/newpost?'], u'externalLinkBlackList': [u'https://linkm.lianjia.com', u'https://lnk0.com', u'https://itunes.apple.com/cn/app/id405882753', u'https://ios.qfang.com', u'https://itunes.apple.com/cn/app/id1225814601', u'wiwjapp://second/detail', u'https://itunes.apple.com/app/id1004322269', u'http://sh.centanet.com/m/app', u'opryz1wu://openlink.cc', u'http://deecq4.openlink.cc', u'https://itunes.apple.com/cn/app/shang-hai-zhong-yuan/id1173813119', u'http://link.dianping.com/universal-link', u'http://m.dianping.com/download', u'https://m.dianping.com/download']}}, u'resultCode': 0}")
]
ERROR 2018-04-27 15:46:24,235 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1651: 登录初始化2-2018_4_27_15_14_14.py:FAILED: error message [', '[By casuse <maxRetryCount>: expected_value:5, actual_values:1 ]', "{u'body': {u'ubt': {u'maxUploadSize': 100, u'sleepTime': 10000, u'minUploadSize': 10, u'basePageTrace': True, u'minUploadTime': 9999, u'maxRetryCount': 1}, u'schema': {u'shareBlackList': [u'http://mobtest.2boss.cn/app_qa/dist/index.html#/index', u'http://mob.2boss.cn/app_qa/dist/index.html#/index', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/hotperson_detail?', u'http://mob.2boss.cn/app_qa/dist/index.html#/hotperson_detail?', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/newpost_one?', u'http://mob.2boss.cn/app_qa/dist/index.html#/newpost_one?', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/newpost?', u'http://mob.2boss.cn/app_qa/dist/index.html#/newpost?'], u'externalLinkBlackList': [u'https://linkm.lianjia.com', u'https://lnk0.com', u'https://itunes.apple.com/cn/app/id405882753', u'https://ios.qfang.com', u'https://itunes.apple.com/cn/app/id1225814601', u'wiwjapp://second/detail', u'https://itunes.apple.com/app/id1004322269', u'http://sh.centanet.com/m/app', u'opryz1wu://openlink.cc', u'http://deecq4.openlink.cc', u'https://itunes.apple.com/cn/app/shang-hai-zhong-yuan/id1173813119', u'http://link.dianping.com/universal-link', u'http://m.dianping.com/download', u'https://m.dianping.com/download']}}, u'resultCode': 0}")
]
INFO 2018-04-27 15:47:36,799 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1638: 登录初始化2-2018_4_27_15_14_14.py:PASS:[time_consuming:0.316727]{ response :  :<maxRetryCount>: expected_value:1, actual_values:1 ]')

INFO 2018-04-27 15:48:19,651 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1638: 登录初始化2-2018_4_27_15_14_14.py:PASS:[time_consuming:0.078056]{ response :  :<resultCode>: expected_value:0, actual_values:{'resultCode': 0, 'maxRetryCount': 1} ]")

INFO 2018-04-27 15:56:30,414 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1638: 登录初始化2-2018_4_27_15_14_14.py:PASS:[time_consuming:0.079299]{ response :  :<{'resultCode': 0, 'maxRetryCount': 1}>: expected_value:{'resultCode': 0, 'maxRetryCount': 1}, actual_values:{'resultCode': 0, 'maxRetryCount': 1} ]")

ERROR 2018-04-27 15:57:42,475 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1651: 登录初始化2-2018_4_27_15_14_14.py:FAILED: error message [', "[By casuse <resultCode>: expected_value:{'resultCode': 1, 'maxRetryCount': 1}, actual_values:{'resultCode': 0, 'maxRetryCount': 1} ]", "{u'body': {u'ubt': {u'maxUploadSize': 100, u'sleepTime': 10000, u'minUploadSize': 10, u'basePageTrace': True, u'minUploadTime': 9999, u'maxRetryCount': 1}, u'schema': {u'shareBlackList': [u'http://mobtest.2boss.cn/app_qa/dist/index.html#/index', u'http://mob.2boss.cn/app_qa/dist/index.html#/index', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/hotperson_detail?', u'http://mob.2boss.cn/app_qa/dist/index.html#/hotperson_detail?', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/newpost_one?', u'http://mob.2boss.cn/app_qa/dist/index.html#/newpost_one?', u'http://mobtest.2boss.cn/app_qa/dist/index.html#/newpost?', u'http://mob.2boss.cn/app_qa/dist/index.html#/newpost?'], u'externalLinkBlackList': [u'https://linkm.lianjia.com', u'https://lnk0.com', u'https://itunes.apple.com/cn/app/id405882753', u'https://ios.qfang.com', u'https://itunes.apple.com/cn/app/id1225814601', u'wiwjapp://second/detail', u'https://itunes.apple.com/app/id1004322269', u'http://sh.centanet.com/m/app', u'opryz1wu://openlink.cc', u'http://deecq4.openlink.cc', u'https://itunes.apple.com/cn/app/shang-hai-zhong-yuan/id1173813119', u'http://link.dianping.com/universal-link', u'http://m.dianping.com/download', u'https://m.dianping.com/download']}}, u'resultCode': 0}")
]
ERROR 2018-04-27 16:09:37,959 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1673: 检查版本信息-2018_4_27_16_9_7.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_4_27_16_9_7.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-04-27 16:11:23,409 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1638: 更新绑定用户信息-2018_4_27_16_11_10.py:PASS:[time_consuming:0.073728]{ response :  :<{'resultCode': 0}>: expected_value:0, actual_values:0 ]")

INFO 2018-04-27 16:14:43,586 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1638: 更新绑定用户信息-2018_4_27_16_11_10.py:PASS:[time_consuming:0.09494]{ response :  :<{'resultCode': 0, 'errMsg': ''}>: expected_value:{'resultCode': 0, 'errMsg': ''}, actual_values:{'resultCode': 0, 'errMsg': u''} ]")

ERROR 2018-05-02 11:33:03,942 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1673: 实时获取tab标签发现（信息）-2018_5_2_11_25_46.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_5_2_11_25_46.py", line 76, in <module>
    headers = {"TBSAccessToken":sys.argv(0)}
TypeError: 'list' object is not callable

INFO 2018-05-02 13:30:12,455 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1645: 实时获取tab标签发现（信息）-2018_5_2_11_25_46.py:PASS:[time_consuming:0.246613]{ response :  :<{'resultCode': 0}>: expected_value:0, actual_values:0 ]")

INFO 2018-05-02 13:35:19,389 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1645: 实时获取tab标签发现（信息）-2018_5_2_13_34_18.py:PASS:[time_consuming:0.232561]{ response :  :<{'resultCode': 0}>: expected_value:0, actual_values:0 ]")

ERROR 2018-05-02 13:35:19,780 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1680: 检查版本信息-2018_5_2_13_34_18.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_2_13_34_18.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-05-02 13:36:15,981 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1645: 实时获取tab标签发现（信息）-2018_5_2_13_34_18.py:PASS:[time_consuming:0.221865]{ response :  :<{'resultCode': 0}>: expected_value:0, actual_values:0 ]")

ERROR 2018-05-02 13:36:16,263 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1680: 检查版本信息-2018_5_2_13_34_18.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_2_13_34_18.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


INFO 2018-05-02 13:38:37,369 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1645: 实时获取tab标签发现（信息）-2018_5_2_13_34_18.py:PASS:[time_consuming:0.232]{ response :  :<{'resultCode': 0}>: expected_value:0, actual_values:0 ]")

ERROR 2018-05-02 13:38:37,641 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1680: 检查版本信息-2018_5_2_13_34_18.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_2_13_34_18.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


ERROR 2018-05-03 15:24:18,786 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1681: 实时获取tab标签发现（信息）-2018_5_3_15_23_36.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/实时获取tab标签发现（信息）-2018_5_3_15_23_36.py", line 24, in testDemo
    r = requests.get(self.protocol + domian  + url,headers=headers, params=param, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {a: 123} must be of type str or bytes, not <type 'int'>


INFO 2018-05-03 15:24:19,365 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1646: 平台框架获取事件列表-2018_5_3_15_23_36.py:PASS:[time_consuming:0.133327]{ response :  :<{'resultCode': 0}>: expected_value:0, actual_values:0 ]")

ERROR 2018-05-03 15:24:19,662 /home/fzyzgong/project/AutoFWOG/AutoFW/views.py views.py views execute_script_result_analysis_fun 1681: 检查版本信息-2018_5_3_15_23_36.py:FAILED: error message [ 未获取脚本执行状态，脚本执行失败 ] Traceback (most recent call last):
  File "/home/fzyzgong/project/AutoFWOG/AutoFW/script/genirtor_script/检查版本信息-2018_5_3_15_23_36.py", line 21, in testDemo
    r = requests.post(self.protocol + domian + url, headers=headers, timeout=8)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/home/fzyzgong/.virtualenvs/AutoFW/local/lib/python2.7/site-packages/requests/utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
InvalidHeader: Value for header {appId: 1} must be of type str or bytes, not <type 'int'>


